# Guition ESP32-S3-4848S040 Music Dashboard
substitutions:
  name: "music-dashboard"
  friendly_name: "Music Dashboard"
  # ha_host: "homeassistant.local"  # Home Assistant hostname (change if HA runs on a different host)
  # ha_port: "8123"  # Home Assistant port (change if HA runs on a non-standard port)

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  music_dashboard:
    url: https://github.com/jtenniswood/esphome-media-player
    files: [guition-esp32-s3-4848s040/packages.yaml]
    ref: main
    refresh: 1s