# Guition ESP32-S3-4848S040 Music Dashboard
substitutions:
  name: "music-dashboard"
  friendly_name: "Music Dashboard"
  # ha_host: "homeassistant.local"  # Home Assistant hostname or IP (change if HA runs on a different host)
  # ha_port: "8123"  # Home Assistant port (change if HA runs on a non-standard port)

# Wifi Setup
wifi:
  ssid: "test"
  password: "test123123"

# Packages
packages:
  - !include packages.yaml
