substitutions:
  name: "media-player"
  friendly_name: "Media Player"
  media_player: ""

esphome:
  name_add_mac_suffix: true

packages:
  music_dashboard: !include ../devices/guition-esp32-p4-jc4880p443/packages-90.yaml

wifi:
  ap:

captive_portal:
