# Guition ESP32-P4-JC8012P4A1 Music Dashboard
substitutions:
  name: "music-dashboard-10inch"
  friendly_name: "Music Dashboard 10inch"
  # ha_host: "homeassistant.local"  # Home Assistant hostname (change if HA runs on a different host)
  # ha_port: "8123"  # Home Assistant port (change if HA runs on a non-standard port)

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  music_dashboard:
    url: https://github.com/jtenniswood/esphome-media-player
    files: [guition-esp32-p4-jc8012p4a1/packages.yaml]
    ref: main
    refresh: 1s
